name: ci

on: [push]

jobs:

  print-x86_64-linux-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cmake .
    - name: build
      run: cmake --build
    - name: run
      run: ./a.out
